name: simple-web-pipeline
on:
    push: 
        branches: [main]
        paths:
            - 'simple_flask/**'
            - '.github/workflows/workflow.yml'
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          image_tag: ${{ steps.docker_build.outputs.image_tag }}
        env:
          TAG: ${{ github.run_id }}
        steps:
            # Repo checkout
            - name: Repo download
              uses: actions/checkout@v4

            # docker hub 로그인
            - name: Login Docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # 빌드
            - name: Build Project
              run: |
                cd simple_flask
                docker build -t ${{ secrets.DOCKER_USERNAME }}/simple_web:${{ env.TAG }} .

            # docker 이미지 push
            - name: Push Docker Image
              id: docker_build
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/simple_web:${{ env.TAG }}
                echo "image_tag=${{ env.TAG }}" >> $GITHUB_OUTPUT


    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
          # checkout manifest repo
          - name: Checkout
            uses: actions/checkout@v4
            with:
              repository: omoknooni/argocd-test

          # Update kubernetes manifest image tag
          - name: Update manifest
            working-directory: ./kubernetes
            run: |
              sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/simple_web:.*|image: ${{ secrets.DOCKER_USERNAME }}/simple_web:${{ needs.build.outputs.image_tag }}|" deployment.yml

          # Commit & Push manifest
          - name: Commit N Push manifest
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              git config --global user.email "actions@github.com"
              git config --global user.name "Github Actions"
              git add .
              git commit -m "Update image tag to ${{ needs.build.outputs.image_tag }}"
              git push origin main
