name: test-cicd
on:
    push: 
        branches: [main]
jobs:
    Build_Project:
        runs-on: ubuntu-latest
        steps:
            - name: Repo download
              uses: actions/checkout@v3
            - name: File Check
              run: cat README.md

            # Runner에 JDK 세팅
            - name: setup JDK
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven

            # 빌드
            - name: Build Project
              run: mvn -B package
              working-directory: ./spring-demo

            # 빌드한 파일을 Artifact로 업로드
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: jar_file
                path: ./spring-demo/*/spring-petclinic-*.jar
    Deploy:
      runs-on: ubuntu-latest
      needs: Build_Project
      steps:
        # Artifact 다운로드
        - name: Get Artifact
          uses: actions/download-artifact@v3
          with:
            name: jar_file
        - name: check
          run: |
            pwd
            ls -al
            file jar_file

        # 배포 서버에 SCP 파일 전송
        - name: Send file with SCP
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.REMOTE_SSH_IP }}
            port: 22
            username: ${{ secrets.REMOTE_SSH_USERNAME }}
            key: ${{ secrets.REMOTE_SSH_PRIVKEY }}
            source: "./spring-petclinic-*.jar"
            target: ${{ secrets.TARGET_PATH }}

        # 전송받은 빌드파일 Deploy
        - name: Deploy with New Version
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.REMOTE_SSH_IP }}
            port: 22
            username: ${{ secrets.REMOTE_SSH_USERNAME }}
            key: ${{ secrets.REMOTE_SSH_PRIVKEY }}
            script: ${{ secrets.TARGET_PATH }}/action-deploy.sh